stm32u5 hal dma_ex function not inlined with GCC 11 or 12
zephyrproject-rtos/trusted-firmware-m pull request #115
Opened 2024-11-07 15:13 UTC by FRASTM

Fix the Issue linked to compilation of file HAL_DMAEx_List_ReplaceNode_Head.c
using a GCC version comprised between v11.x and v12.x.

and blocking the zephyr CI

Issue is seen only with TF-M build config RelWithDebInfo (With MinSizeRel config, this file is not built).
Issue could be fixed by "adding attribute ((no_inline)) to DMA_List_CheckNodesBaseAddresses allows the build to pass"

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/80932

2024-11-07 15:38 UTC, FRASTM commented
see https://github.com/FRASTM/trusted-firmware-m/pull/1

2024-11-08 07:48 UTC, tomi-font requested changes
- Did you submit this fix upstream? I could not find anything with the `Change-Id` mentioned.
- When this is done, make sure to cherry pick the upstream commit into the Zephyr fork by using the `-x` option of `git cherry-pick` to keep track of the cherry-picked commit.
- This PR is not quite solving the issue in Zephyr by itself. The issue will be solved in Zephyr once this PR is merged and that commit is integrated into Zephyr. For that you will need to create a manifest PR in the Zephyr repository (see PRs with the `manifest-trusted-firmware-m` label for examples), and there you can have the `Fixes X`.

2024-11-12 14:36 UTC, FRASTM commented
> * Did you submit this fix upstream? I could not find anything with the `Change-Id` mentioned.
> * When this is done, make sure to cherry pick the upstream commit into the Zephyr fork by using the `-x` option of `git cherry-pick` to keep track of the cherry-picked commit.
> * This PR is not quite solving the issue in Zephyr by itself. The issue will be solved in Zephyr once this PR is merged and that commit is integrated into Zephyr. For that you will need to create a manifest PR in the Zephyr repository (see PRs with the `manifest-trusted-firmware-m` label for examples), and there you can have the `Fixes X`.

@tomi-font 
fix upstream is https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/33420

2024-11-13 06:59 UTC, tomi-font commented
First, where in Zephyr would you like this fix to be included? `v3.7-branch` or `main`? (Or both?)

And I'm not sure I get what you're saying, but it's normal that the end commit hashes differ even when cherry picking the commit (because the two branches are not identical.)

Anyway, we'll want to wait for your patch to be approved upstream before merging it here.

2024-11-22 12:43 UTC, erwango commented
> Anyway, we'll want to wait for your patch to be approved upstream before merging it here.

@tomi-font TF-M upstream team won't integrate the change until PR is merged and delivered in official HAL package (they don't merge HAL fixes). See https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/33420.
I don't think we can afford to wait that long for current PR. Can we consider merging it faster ?

2024-12-02 14:39 UTC, FRASTM commented
commit msg now mentions the reference for the cherry picked

2024-12-04 10:35 UTC, FRASTM commented
> Please make the changes identical between this PR and your upstream one. Also, you will need a PR in Zephyr to update the reference to this repo in order to pull those changes in. While this PR is not merged, the `revision` should be `pull/115/head`.

done in https://github.com/zephyrproject-rtos/zephyr/pull/82534

2024-12-16 13:56 UTC, tomi-font approved these changes

2024-12-16 14:00 UTC, erwango approved these changes

2025-02-04 08:50 UTC, merged