Remove Ethos patches
zephyrproject-rtos/trusted-firmware-m pull request #118
Opened 2024-12-23 17:58 UTC by wearyzen

2025-01-06 11:11 UTC, ithinuel approved these changes

2025-01-07 12:30 UTC, tomi-font requested changes
- The two commits are not identical in diff compared to their upstream counterparts. Please make them clean cherry picks.
- Also, please cherry pick them with the `-x` flag so that we know from the commit message that those commits are cherry picks and from which upstream commits.

2025-01-08 11:29 UTC, wearyzen commented
> * The two commits are not identical in diff compared to their upstream counterparts. Please make them clean cherry picks.
> * Also, please cherry pick them with the `-x` flag so that we know from the commit message that those commits are cherry picks and from which upstream commits.

Hi @tomi-font, thank you for the review. I have updated the commit message and the PR description to reflect that corstone320 changes are skipped from the cherry-pick.

2025-01-08 11:34 UTC, tomi-font commented
> Hi @tomi-font, thank you for the review. I have updated the commit message and the PR description to reflect that corstone320 changes are skipped from the cherry-pick.

What is the reason for skipping those changes? Is the skipping needed?

2025-01-08 12:54 UTC, wearyzen commented
> > Hi @tomi-font, thank you for the review. I have updated the commit message and the PR description to reflect that corstone320 changes are skipped from the cherry-pick.
> 
> What is the reason for skipping those changes? Is the skipping needed?

The first commit "npu: Update NPU driver to version 24.08" expects that `platform/ext/target/arm/mps4/corstone320/target_cfg.c` is already present but since corstone320 support is not available the cherry-pick isn't a clean and it needs more commits to bring int which becomes a big tasks that it has to be. I think it would make sense to bring those changes when the support for corstone320 is added or when the tfm is updated to the latest version.

2025-01-13 08:07 UTC, tomi-font approved these changes
I see. Makes sense. Thanks for the expanation.

2025-01-15 08:20 UTC, merged