Tfm upmerge to v.1.3.99 with important fixes for v2.6
zephyrproject-rtos/trusted-firmware-m pull request #52
Opened 2021-05-20 15:16 UTC by ioannisg

This brings in several fixes. Most important, it formally updates PSA crypto headers, after TFM has switched to Mbedtls 2.26. In addition, it fixes some cache-enabling issues for nRF platforms.

2021-05-20 15:17 UTC, ioannisg commented
Side note: I am going to try upstream the STM downstream patch, so we won't have to keep including it after the upmerges.

2021-05-20 15:22 UTC, galak commented on README.rst
> +    commit: eeba9de2f5c19293038d7d551cc0ceffe32d8992..
why the `..` at end?

2021-05-20 15:22 UTC, galak commented on README.rst
> +    commit: cd3f3caf3a5bbb543af2206056668422f4e135b9.
why `.` at end?

2021-05-20 15:22 UTC, galak commented on init-git.sh
> +PSA_ARCH_TESTS_GIT_SHA=cd3f3caf3a5bbb543af2206056668422f4e135b9.
what the `.` at end?

2021-05-20 17:03 UTC, ioannisg reviewed
Sorry about the dots, @galak, will fix :)

2021-05-20 17:32 UTC, ioannisg commented
> This update seems to break support with `lpcxpresso55s69_ns` ... file size is much smaller , and binary doesn't run. Seems to be an upstream problem. Tested with `$ west build -p auto -b lpcxpresso55s69_ns samples/tfm_integration/psa_level_1`. Trying to see what's broken upstream.

Thanks. In the mean time I will test on NRF and STm boards. I 've added the Block:HW test label in the manifest PR.

2021-05-21 12:42 UTC, anangl approved these changes

2021-05-25 12:16 UTC, galak requested changes
The tfm repo deleted files that this PR doesn't delete as well.  Please fix this.

2021-05-25 16:52 UTC, galak approved these changes

2021-05-25 17:36 UTC, microbuilder approved these changes
Tested on:

- lpcxpresso5s69_ns
- mps2_an521_nonsecure

2021-05-26 19:16 UTC, ioannisg commented
@microbuilder your commit was cherry-picked, can you take a look?

2021-05-26 21:28 UTC, merged