platform: stm32u5xx: target_cfg: SAU should extend NS to full flash
zephyrproject-rtos/trusted-firmware-m pull request #84
Opened 2023-01-31 15:04 UTC by erwango

Update NON_SECURE_LIMIT to cover full flash (beyond FLASH_BASE_NS). It will help SAU to set this section to NS.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/53231

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>
Change-Id: I144e1a6adba3d61dd50ec4fe55fe774d5c78e121

2023-02-03 10:49 UTC, microbuilder commented
This needs to go upstream first to TF-M. Do you mind making a change request for that?

2023-02-06 13:55 UTC, erwango commented
@microbuilder replaced my commit with the upstream one.

2023-02-06 15:38 UTC, microbuilder approved these changes

2023-02-06 15:41 UTC, microbuilder requested changes
Sorry, approved too soon. Can you put the cherry pick in the commit message, referencing the upstream commit? Here's an example of how we usually do that: https://github.com/zephyrproject-rtos/trusted-firmware-m/pull/68/commits

2023-02-06 15:57 UTC, microbuilder approved these changes

2023-02-07 09:35 UTC, merged